# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- preview

# no PR builds
pr: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  displayName: 'Powershell Script'
  inputs:
    targetType: filePath
    filePath: ./build/applyVersionSuffix.ps1

- script: dotnet --info
  displayName: 'dotnet info'

- script: dotnet build -c $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack -c $(buildConfiguration) src/WeihanLi.Redis/WeihanLi.Redis.csproj -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet pack $(buildConfiguration)' 

- script: dotnet nuget push $(Build.ArtifactStagingDirectory)\*.nupkg -k $(nugetApiKey) -s $(nugetSourceUrl)
  displayName: 'dotnet nuget push'