# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- previewpool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: Bash@3
  displayName: 'Bash Script'
  inputs:
    targetType: filePath
    filePath: ./build/applyVersionSuffix.sh

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack --configuration $(buildConfiguration) -o out ./src/WeihanLi.Redis/WeihanLi.Redis.csproj
  displayName: 'dotnet pack $(buildConfiguration)' 

- script: dotnet nuget push ./*.nupkg -k $(nugetApiKey) -s $(nugetSourceUrl)
  displayName: 'dotnet nuget push'